logging:
  level:
    root: INFO

spring:
  profiles:
    include:
      - common, config, repository

jwt:
  private-key: 
  public-key:
  refreshExpireTime: 86400000 #1일
  accessExpireTime: 1800000 #30분
