spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2: 
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        ddl-auto: none