spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/refund-test
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  h2: 
    console:
      enabled: true
      path: /h2-console