spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

szs:
  names:
    - 홍길동
    - 김둘리
    - 마징가
    - 베지터
    - 손오공
  regNos:
    - 860824-1655068
    - 921108-1582816
    - 880601-2455116
    - 910411-1656116
    - 820326-2715702

api:
  infos:
    - /h2-console/**
    - /szs/signup
    - /szs/login
    - /v3/api-docs/**
    - /swagger-ui/**
    - /v2/api-docs
    - /swagger-resources
    - /swagger-resources/**
    - /configuration/ui
    - /configuration/security
    - /swagger-ui.html
    - /webjars/**